#!/bin/bash

set -e

ROOT_DIR=$(pwd)

if [[ -z "$1"  ]]; then
    echo "Available commands:
         prepare - Creates a build.ninja file
         build - Builds the firmware"
    exit 1
fi

sh $ROOT_DIR/build/$1.sh ${@:2}
